### ISSUE TITLE
Add authentication

### ISSUE THREAD

**Issue by SoulRaven80** [SoulRaven80/wDOSg#1]
Login screen plus authentication:
-- Remember me option ?
-- Default admin user
-- Change password for admin (first login)

Restrict direct access without auth information

**Comment by MarcusEstr** [comment]
@SoulRaven80  Hi, I was using the previous version of wdosg (pre-login) and it was working well in my Docker container. I updated to v1.1.0 and do not have a login, so am unable to login. In case this was an issue with having my previous install, I setup a new container and initialized that one but am still running into the same thing. What are the default admin user credentials or how can I access them? There doesn't seem to be a process to set up an initial account (at least as far as I can see in my new instance).

If it helps, when the Docker container is up and running, wdosg's startup logs say the following: 
DB setup: Creating tables
DB setup: Populating genres
DB setup: Populating companies
DB setup: Populating dos_games
DB setup: Populating users
DB setup: Clearing expired authentication tokens
Application ready. Server listening on port 3001.  

 Thank you for your help!

**Comment by SoulRaven80** [comment]
Hi @MarcusEstr ,

Thanks for using wDOSg and I hope you are enjoying it!

With this authentication change, default admin user / password are: **wdosg@wdosg.com / wdosg**.

You can always change the default password through the option under the new user menu on the header once logged in.

Other changes are reflected on the README as well (such as logging level or encryption token secret).

Let me know if you have any other issues!

**Comment by MarcusEstr** [comment]
Thanks for the quick response!! All good now :).
