### ISSUE TITLE
Request: one step import method

### ISSUE THREAD

**Issue by hargrove4570** [SoulRaven80/wDOSg#10]
First time using jsdos and was held up a bit making the bundle (like adding the startup exe to the bundle config). If making the bundle can be done all within wdosg that's be better.

Also, might want to post an example curl to get the twitch token:

```
curl -X POST https://id.twitch.tv/oauth2/token \
-H 'Content-Type: application/x-www-form-urlencoded' \
-d 'grant_type=client_credentials&client_id=YOUR_ID_HERE&client_secret=YOUR_SECRET_HERE'
```

**Comment by jdeath** [comment]
Finally got it working. Runs well. Thanks for this project.

Any reason to not have it just take the client_id and secret? Not sure why need the extra step. The token has an expiration, but not sure if it is enforced. I used above curl command in a bash script to set the environment variable. 
```
TWITCH_CLIENT_ID=XXXXXX
TWITCH_CLIENT_SECRET=YYYYYY

COMMAND="curl -X POST https://id.twitch.tv/oauth2/token -H 'Content-Type: application/x-www-form-urlencoded' -d 'grant_type=client_credentials&client_id=$TWITCH_CLIENT_ID&client_secret=$TWITCH_CLIENT_SECRET' | jq -r '.access_token'"

TWITCH_APP_ACCESS_TOKEN=$(eval "$COMMAND")
export TWITCH_APP_ACCESS_TOKEN="${TWITCH_APP_ACCESS_TOKEN}"
```

**Comment by SoulRaven80** [comment]
Glad you could make it work!

I'm currently adding a feature to generate the bundles within the app, so no other steps are involved outside wdosg.
Regarding the token, the underlying library that we use to connect to IGDB requires the token and not the secret (for security reasons), so we need to stick with that.

Will add the curl command to the readme for easier of use. Thanks!

**Comment by SoulRaven80** [comment]
You might want to try the new option under "Settings / Create new bundle"

 For now, importing a game would be done in two steps:

1. Generating the jsdos bundle file
2. Importing the bundle into the library

Code is updated, and a new Docker version of is published under **soulraven1980/wdosg:latest**

Thanks!

**Comment by SoulRaven80** [comment]
I've added an option to start from a zipped game and using the wizard to have the game uploaded over the library in one fell swoop.

@hargrove4570 if you have the time, please check the feature under settings.
Closing this issue for now!
Thanks :)

**Comment by hargrove4570** [comment]
Works perfect and I actually like the options to change the dosbox settings before import

**Comment by jdeath** [comment]
Bundle creation worked Perfect. So awesome!!

I made it available to home assistant users with a one-click install. My version adds curl/jq into your docker, so the user just needs to add the client/secret and it will automatically pull the token. If you ever get to making a github release, that will make it easier to track when you add new capability.

https://github.com/jdeath/homeassistant-addons/blob/main/wdosg/README.md
