### ISSUE TITLE
Show progress spinner while downloading from DOS.Zone

### ISSUE THREAD

**Issue by jhelmink** [SoulRaven80/wDOSg#15]
Downloads from DOS.Zone can be slow for large files.

There is no indication that the download is pending in the UI.

**Comment by SoulRaven80** [comment]
Thanks for catching this up!

A new version (v1.1.2) is released with the corresponding change. Please try it and let me know!
Closing this issue for now.

**Comment by jhelmink** [comment]
This is a much nicer experience now!
