### ISSUE TITLE
Use optional URL param for Page Number when browsing DOS.Zone games

### ISSUE THREAD

**Issue by jhelmink** [SoulRaven80/wDOSg#16]
So you can quickly skip to a specific page.

**Comment by SoulRaven80** [comment]
Added that feature so the filter can be applied through the URL, with the following query params:

action=import
page=<NUMBER OF PAGE>
filter=<TEXT TO USE AS A FILTER FOR RESULTS>

This is already included in release v1.1.2.
Thanks!
