### ISSUE TITLE
Feature request:  Add section for game manual

### ISSUE THREAD

**Issue by mikesellt** [SoulRaven80/wDOSg#19]
Would it be possible to add a section in the game screen where a user/admin can upload a copy (pdf, jpg, etc...) of the pages of the manual for each game?  Some of these old games had the section of the manual that aided in proving ownership of the game somehow (what is the 3rd word on line 7 of page 4 or something similar).  Some other games had pages of maps, hints, cheat codes, etc... that could also be helpful.  

Thanks!

**Comment by SoulRaven80** [comment]
Ohhh that's a GREAT idea!
Thanks for that suggestion, will work in that!

**Comment by SoulRaven80** [comment]
I've just released version 1.2.0, which includes this great feature.

Different files can be uploaded in the settings section (only by admins), but attachments can be seen / downloaded in the game details screen by all users.

Cheers!
