### ISSUE TITLE
Database Path

### ISSUE THREAD

**Issue by jdeath** [SoulRaven80/wDOSg#9]
Neat project. Be great if `getDbPath()` path also can use an environment variable just like `getGamesLibraryLocation()` . I would do a PR, but haven't had a chance to test. Having a variable allows me to integrate as a home assistant addon with less issues.

**Comment by SoulRaven80** [comment]
I don't use home assistant but adding an env variable for the DB was on the TODO list.
Not sure how will that integrate, but I'll make the change anyway
